server:
  servlet:
    context-path: /Arslinth
    session:
      #session过期时间（秒）
      timeout: 1800
  connection-timeout: 10000
  port: 8600
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
  # thymeleaf配置
  thymeleaf:
    cache: false
  session:
    store-type: redis
  datasource:
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 1234
  #  jackson:
  #    date-format: yyyy年MM月dd日
  #    time-zone: GMT+8
  servlet:
    multipart:
      #最大单个上传文件大小
      max-file-size: 3MB
      #最大总文件上传大小
      max-request-size: 10MB
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  # 关闭mybatis-plus的banner打印
  global-config:
    banner: false
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
#登录图形验证码有效时间(单位分钟)/宽度/高度/位数
loginCode:
  expiration: 5
  width: 111
  height: 36
  digit: 2
# security 配置
security:
  #同一账号，最大登录数
  max-session: 10
  # 超出最大登录数，是否阻止登录
  prevents-login: false
  #记住我到期时间（秒）
  rememberExpireTime: 84600

